version: '2'
services:
    hao-app:
        image: hao
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://hao-postgresql:5432/hao
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hao-postgresql:
        extends:
            file: postgresql.yml
            service: hao-postgresql
